version: "1.0"

services:
  bottrading:
    image: ahmadoustoura/bottrading:v1
    command: ["python", "bot.py"]
    env:
      - name: ULIMIT_NOFILE
        value: "65536:65536"
    parameters:
      storage:
        - name: data
          mount: /app/data
          readOnly: false

profiles:
  compute:
    bottrading:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
      attributes:
        system/ulimit_nofile: "65536"
        system/inotify_max_user_watches: "524288"

  placement:
    bottrading:
      cluster:
        match:
          region: akash

deployment:
  bottrading:
    profile: bottrading
    count: 1
#