version: "2.0"

services:
  bottrading:
    image: ahmadoustoura/bottrading:v1
    command: ["python", "bot.py"]
    env:
      - name: PYTHONUNBUFFERED
        value: "1"
    expose:
      - port: 80
        proto: tcp
        service: bottrading

profiles:
  compute:
    bottrading:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
      attributes:
        system/ulimit_nofile: "65536"
        system/inotify_max_user_watches: "524288"

  placement:
    bottrading:
      pricing:
        amount: 5000
        denom: uakt
      constraints:
        - region == worldwide

deployment:
  bottrading:
    profile: bottrading
    count: 1