---
version: "2.0"

services:
  bot:
    image: docker.io/Ahmadoustour/mybot:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    bot:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi

  placement:
    dcloud:
      attributes:
        region: any
      pricing:
        bot:
          denom: uakt
          amount: 10000  # يعادل تقريبًا 0.01 ATOM/يوم

deployment:
  bot:
    dcloud:
      profile: bot
      count: 1

