---
version: "2.0"

services:
  bot:
    image: yourdockerhubusername/mybot:latest
    command: ["python", "bot.py"]
    expose: []

profiles:
  compute:
    bot:
      resources:
        cpu:
          units: 1
        memory:
          size: 4Gi
        storage:
          size: 20Gi

  placement:
    akash:
      attributes:
        region: any
      pricing:
        bot:
          denom: uakt
          amount: 10000

deployment:
  bot:
    akash:
      profile: bot
      count: 1
