version: "4.0"

services:
  bottrading:
    image: ahmadoustoura/bottrading:v4
    command: ["python", "bot.py"]

profiles:
  compute:
    bottrading:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi

  placement:
    bottrading:
      cluster:
        match:
          region: akash

deployment:
  bottrading:
    profile: bottrading
    count: 1
